name: Release
on:
  push:
    tags:
      - "v*"

jobs:

  build-on-ubuntu2204:
    runs-on: ubuntu-22.04
    name: build on ubuntu-22.04 x86_64
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21.0'
      - name: Install Compilers
        run: |
          sudo apt-get update
          kernel_ver=`uname -r | cut -d'-' -f 1`
          sudo apt-get install --yes build-essential pkgconf libelf-dev llvm-14 clang-14 linux-tools-common linux-tools-generic gcc gcc-aarch64-linux-gnu linux-source-${kernel_ver}
          for tool in "clang" "llc" "llvm-strip"
          do
            sudo rm -f /usr/bin/$tool
            sudo ln -s /usr/bin/$tool-14 /usr/bin/$tool
          done
          cd /usr/src
          sudo tar -xf linux-source-${kernel_ver}.tar.bz2
          cd /usr/src/linux-source-${kernel_ver}
          test -f .config || sudo make oldconfig
          sudo make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- prepare V=0
          ls -al /usr/src/linux-source-${kernel_ver}
        shell: bash
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: authenticate
        run: |
          gh auth login --with-token <<<'${{ secrets.GITHUB_TOKEN }}'
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          configuration: "configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Write File
        uses: DamianReeves/write-file-action@v1.2
        with:
          path: ./bin/release_notes.txt
          contents: |
            ${{ steps.github_release.outputs.changelog }}
          write-mode: append
      - name: Release amd64
        run: |
          make clean
          make env
          make -f builder/Makefile.release release SNAPSHOT_VERSION=${{ steps.get_tags.outputs.VERSION }}
      - name: Release arm64 (CROSS COMPILATION)
        run: |
          make clean
          make env
          CROSS_ARCH=arm64 make -f builder/Makefile.release release SNAPSHOT_VERSION=${{ steps.get_tags.outputs.VERSION }}
      - name: Publish
        run: |
          make -f builder/Makefile.release publish SNAPSHOT_VERSION=${{ steps.get_tags.outputs.VERSION }}
